Repository autobrr/autobrr, pull requests merged in 2021-12, with the labels that each got.

#45 Indexers: Add TD, MTV, TS and Milkie
  internal/indexer/definitions/milkie.yaml
  internal/indexer/definitions/morethantv.yaml
  internal/indexer/definitions/torrentday.yaml
  internal/indexer/definitions/torrentseeds.yaml
Labels: indexers

#50 Fix: Announce parse queue
  internal/announce/announce.go
  internal/irc/handler.go
Labels: bug, backend

#51 Fix(indexers): Milkie url encode apikey and add tests
  internal/announce/announce_test.go
  internal/indexer/definitions/milkie.yaml
Labels: bug, enhancement, backend

#52 Feature: List releases
  internal/database/release.go
  internal/domain/release.go
  internal/http/release.go
  internal/release/service.go
  web/src/domain/interfaces.ts
  web/src/screens/Base.tsx
  web/src/screens/Releases.tsx
Labels: enhancement, web, backend
