Repository autobrr/autobrr, pull requests merged in 2022-12, with the labels that each got.

#545 fix(web/filters): truncate too long name
  web/src/components/modals/index.tsx
  web/src/screens/filters/details.tsx
Labels: enhancement, web

#522 fix(web): download client table overflow
  web/src/screens/settings/DownloadClient.tsx
Labels: enhancement, web

#555 feat(tools): Add a simple MockIndexer helper for IRC announcing and indexing
  test/definitions/mock.yaml
  test/mockindexer/README.md
  test/mockindexer/files/.gitignore
  test/mockindexer/irc/client.go
  test/mockindexer/irc/handlers.go
  test/mockindexer/irc/server.go
  test/mockindexer/main.go
Labels: enhancement, backend, indexers, irc, testing

#556 feat(web): When adding the first action, display it in edit mode
  web/src/screens/filters/action.tsx
Labels: web, filters, actions

#557 fix(announce): parse torrentUrl
  internal/domain/indexer.go
  internal/domain/indexer_test.go
Labels: bug, backend, irc

#558 feat(clients): add support for qBittorrent 4.4.0+
  go.mod
  go.sum
  internal/action/qbittorrent.go
  internal/action/run.go
  internal/action/service.go
  internal/domain/client.go
  internal/domain/client_test.go
  internal/domain/release.go
  internal/download_client/connection.go
  internal/download_client/service.go
  internal/http/download_client.go
  internal/release/service.go
  pkg/qbittorrent/client.go
  pkg/qbittorrent/client_test.go
  pkg/qbittorrent/domain.go
  pkg/qbittorrent/domain_test.go
  pkg/qbittorrent/methods.go
Labels: enhancement, backend, Download client, actions

#560 feat(actions): simplify macro parsing
  internal/action/deluge.go
  internal/action/exec.go
  internal/action/exec_test.go
  internal/action/lidarr.go
  internal/action/qbittorrent.go
  internal/action/radarr.go
  internal/action/readarr.go
  internal/action/rtorrent.go
  internal/action/run.go
  internal/action/sonarr.go
  internal/action/transmission.go
  internal/action/whisparr.go
  internal/domain/action.go
  internal/domain/client.go
  internal/domain/macros.go
  internal/download_client/connection.go
  internal/download_client/service.go
  pkg/lidarr/client.go
  pkg/lidarr/lidarr.go
  pkg/lidarr/lidarr_test.go
  pkg/radarr/client.go
  pkg/radarr/radarr.go
  pkg/radarr/radarr_test.go
  pkg/readarr/client.go
  pkg/readarr/readarr.go
  pkg/readarr/readarr_test.go
  pkg/sonarr/client.go
  pkg/sonarr/sonarr.go
  pkg/sonarr/sonarr_test.go
  pkg/whisparr/client.go
  pkg/whisparr/whisparr.go
Labels: enhancement, backend, actions

#561 feat(indexers): UHDBits support new format
  internal/indexer/definitions/uhdbits.yaml
Labels: indexers, irc

#563 feat(filters): smart episode
  cmd/autobrr/main.go
  internal/database/filter.go
  internal/database/postgres_migrate.go
  internal/database/release.go
  internal/database/sqlite_migrate.go
  internal/domain/filter.go
  internal/domain/release.go
  internal/filter/service.go
  internal/release/service.go
  web/src/screens/filters/details.tsx
  web/src/types/Filter.d.ts
Labels: enhancement, backend, filters

#564 feat(releases): implement keyword search
  internal/database/release.go
Labels: web, backend, releases

#565 fix(releases): improve load time by 47x
  internal/database/release.go
Labels: enhancement, backend, database

#579 fix(indexers): TS regex
  internal/indexer/definitions/torrentseeds.yaml
Labels: bug, backend, indexers, irc

#582 fix(indexers): fix AR and TS (GER) regex patterns
  internal/indexer/definitions/alpharatio.yaml
  internal/indexer/definitions/torrentsyndikat.yaml
Labels: bug, backend, indexers, irc

#584 feat(web): added missing placeholders
  web/src/screens/filters/action.tsx
  web/src/screens/filters/details.tsx
Labels: enhancement, web, filters

#586 fix(indexers): bad ncore torrent URL
  internal/indexer/definitions/ncore.yaml
Labels: bug, backend, indexers, irc

#587 feat(http): log invalid login attempts
  cmd/autobrr/main.go
  internal/auth/service.go
  internal/database/user.go
  internal/http/auth.go
  internal/http/server.go
Labels: enhancement, backend, api

#569 refactor(database): clean-up queries
  internal/database/action.go
  internal/database/api.go
  internal/database/database.go
  internal/database/download_client.go
  internal/database/feed.go
  internal/database/feed_cache.go
  internal/database/filter.go
  internal/database/indexer.go
  internal/database/irc.go
  internal/database/notification.go
  internal/database/release.go
  internal/database/user.go
Labels: enhancement, backend, database

#593 feat(indexers): add CRT (Cathode-Ray Tube)
  internal/indexer/definitions/cathode-ray-tube.yaml
Labels: enhancement, backend, indexers, irc

#596 feat(http/releases): report errors to end-users.
  internal/http/release.go
Labels: enhancement, backend, releases, api

#594 feat(indexers): Add DocsPedia.world
  internal/indexer/definitions/docspedia.yaml
Labels: backend, indexers, irc

#597 feat(http): improve invalid login handling
  internal/auth/service.go
  internal/http/auth.go
Labels: backend, api

#599 fix(database): fix filter regression from clean-up
  internal/database/action.go
  internal/database/filter.go
  internal/database/release.go
Labels: bug, backend, filters, database
