Repository autobrr/autobrr, pull requests merged in 2022-10, with the labels that each got.

#484 feat(rss): implement relative URL support
  .github/workflows/release.yml
  Dockerfile
  Dockerfile.ci
  go.mod
  internal/feed/rss.go
  internal/feed/rss_test.go
Labels: enhancement, backend, feeds

#456 feat(feed): Add field for setting request timeout
  internal/database/feed.go
  internal/database/postgres_migrate.go
  internal/database/sqlite_migrate.go
  internal/domain/feed.go
  internal/feed/rss.go
  internal/feed/service.go
  pkg/torznab/torznab.go
  web/src/forms/settings/FeedForms.tsx
  web/src/forms/settings/IndexerForms.tsx
  web/src/types/Feed.d.ts
Labels: enhancement, backend, feeds

#494 fix(indexers): EMP parse line patterns
  internal/indexer/definitions/emp.yaml
Labels: bug, backend, indexers, irc

#496 build: images with goreleaser
  .github/workflows/release.yml
  .goreleaser.yml
  goreleaser.Dockerfile
Labels: build

#477 fix(indexers): improve ab parsing
  go.mod
  go.sum
  internal/announce/announce.go
  internal/domain/indexer.go
  internal/domain/release.go
  internal/indexer/definitions/animebytes.yaml
Labels: backend, indexers

#495 fix(indexers): SpeedApp download url
  internal/indexer/definitions/speedapp.yaml
Labels: bug, backend, indexers, irc

#490 feat(clients): add Readarr support
  README.md
  internal/action/readarr.go
  internal/action/run.go
  internal/domain/action.go
  internal/domain/client.go
  internal/download_client/connection.go
  internal/indexer/definitions/myanonamouse.yaml
  pkg/readarr/client.go
  pkg/readarr/readarr.go
  pkg/readarr/readarr_test.go
  pkg/readarr/testdata/release_push_ok_response.json
  pkg/readarr/testdata/system_status_response_ok.json
  web/src/domain/constants.ts
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/screens/filters/action.tsx
  web/src/types/Download.d.ts
Labels: enhancement, backend, Download client, actions

#474 feat(web): better tooltips and uniformity
  web/package.json
  web/src/components/Checkbox.tsx
  web/src/components/data-table/Buttons.tsx
  web/src/components/data-table/Cells.tsx
  web/src/components/emptystates/index.tsx
  web/src/components/fields/text.tsx
  web/src/components/inputs/input.tsx
  web/src/components/inputs/input_wide.tsx
  web/src/components/inputs/radio.tsx
  web/src/components/inputs/select.tsx
  web/src/components/inputs/switch.tsx
  web/src/components/inputs/text.tsx
  web/src/components/modals/index.tsx
  web/src/components/notifications/Toast.tsx
  web/src/components/panels/index.tsx
  web/src/components/tooltips/Tooltip.tsx
  web/src/forms/filters/FilterAddForm.tsx
  web/src/forms/settings/APIKeyAddForm.tsx
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/forms/settings/IndexerForms.tsx
  web/src/forms/settings/IrcForms.tsx
  web/src/forms/settings/NotificationForms.tsx
  web/src/hooks/hooks.ts
  web/src/screens/Base.tsx
  web/src/screens/Logs.tsx
  web/src/screens/Settings.tsx
  web/src/screens/auth/login.tsx
  web/src/screens/auth/onboarding.tsx
  web/src/screens/dashboard/ActivityTable.tsx
  web/src/screens/filters/action.tsx
  web/src/screens/filters/details.tsx
  web/src/screens/filters/list.tsx
  web/src/screens/releases/Filters.tsx
  web/src/screens/releases/ReleaseTable.tsx
  web/src/screens/settings/Action.tsx
  web/src/screens/settings/Api.tsx
  web/src/screens/settings/DownloadClient.tsx
  web/src/screens/settings/Feed.tsx
  web/src/screens/settings/Indexer.tsx
  web/src/screens/settings/Irc.tsx
  web/src/screens/settings/Notifications.tsx
  web/tailwind.config.js
  web/yarn.lock
Labels: web

#502 feat(feeds): improve RSS
  internal/database/feed.go
  internal/database/feed_cache.go
  internal/database/postgres_migrate.go
  internal/database/sqlite_migrate.go
  internal/domain/feed.go
  internal/feed/client.go
  internal/feed/rss.go
  internal/feed/rss_test.go
  internal/feed/service.go
  internal/feed/torznab.go
  internal/release/service.go
  pkg/torznab/torznab_test.go
  web/src/forms/settings/FeedForms.tsx
  web/src/screens/settings/Feed.tsx
  web/src/types/Feed.d.ts
Labels: web, backend, feeds

#503 feat(indexers): add iPlay / RMT
  internal/indexer/definitions/iplay.yaml
Labels: enhancement, backend, indexers

#504 feat(indexers): add Enthralled
  internal/indexer/definitions/enthralled.yaml
Labels: enhancement, backend, indexers

#506 feat(filters): filtering for raw releaseTags
  internal/database/filter.go
  internal/database/postgres_migrate.go
  internal/database/sqlite_migrate.go
  internal/domain/filter.go
  internal/domain/filter_test.go
  web/src/screens/filters/details.tsx
  web/src/types/Filter.d.ts
Labels: enhancement, web, backend, filters

#491 feat(releases): retry failed downloads
  .github/workflows/release.yml
  internal/action/deluge.go
  internal/action/qbittorrent.go
  internal/action/rtorrent.go
  internal/action/transmission.go
  internal/client/http.go
  internal/domain/release.go
  internal/domain/release_test.go
  internal/domain/testdata/archlinux-2011.08.19-netinstall-i686.iso.torrent
  internal/filter/service.go
Labels: backend

#508 build: revert to old way of docker job
  .github/workflows/release.yml
  .goreleaser.yml
Labels: docker, build

#510 fix(filters): except categories
  internal/domain/filter.go
  internal/domain/filter_test.go
Labels: bug, backend, filters

#512 feat(indexers): Improve arr compatability for animebytes
  internal/indexer/definitions/animebytes.yaml
Labels: enhancement, backend, indexers

#514 fix(filters): max downloads per hour check
  internal/database/filter.go
  internal/database/release.go
Labels: bug, backend, filters, releases

#515 feat(actions): watch dir rename file
  internal/action/run.go
Labels: enhancement, backend, actions
