Repository autobrr/autobrr, pull requests merged in 2022-07, with the labels that each got.

#329 fix(releases): ParseReleaseTags container matching
  internal/domain/releasetags.go
  internal/domain/releasetags_test.go
Labels: bug, backend, releases

#331 fix(web): auth fallback to login instead of error
  web/src/api/APIClient.ts
Labels: enhancement, web, backend

#332 fix(indexers): torznab update not working
  internal/indexer/service.go
Labels: bug, backend, indexers

#333 feat(irc): attempt SASL login with fallback to nickserv
  internal/irc/handler.go
  test/integration/ircd.yaml
Labels: enhancement, backend, irc

#337 fix(indexers): mtv tags to category parsing
  internal/indexer/definitions/morethantv.yaml
Labels: bug, backend, indexers

#335 feat(macros): add FilterName
  internal/action/macros.go
Labels: enhancement, backend, actions

#338 feat(releases): action status show filter and client
  internal/action/run.go
  internal/database/migrate.go
  internal/database/release.go
  internal/domain/release.go
  web/src/components/data-table/Cells.tsx
  web/src/components/tooltips/Tooltip.tsx
  web/src/screens/releases/ReleaseTable.tsx
  web/src/types/Release.d.ts
Labels: enhancement, web, backend, actions, releases

#344 fix(download-clients): qbit panic on nil logger
  internal/action/qbittorrent.go
  internal/action/run.go
  internal/action/service.go
  pkg/qbittorrent/client.go
  pkg/qbittorrent/methods.go
Labels: bug, backend, Download client, actions

#345 fix(database): migration missing types
  internal/database/postgres_migrate.go
  internal/database/sqlite_migrate.go
Labels: bug, backend, database

#346 fix(feeds): torznab update and delete
  internal/database/feed_cache.go
  internal/domain/feed.go
  internal/feed/service.go
  internal/feed/torznab.go
  internal/indexer/service.go
  internal/release/service.go
Labels: bug, backend, feeds

#347 feat(feeds): torznab add test button
  internal/feed/service.go
  internal/feed/torznab.go
  internal/http/feed.go
  pkg/torznab/caps.go
  pkg/torznab/client.go
  pkg/torznab/feed.go
  pkg/torznab/testdata/caps_response.xml
  pkg/torznab/torznab.go
  pkg/torznab/torznab_test.go
  web/src/api/APIClient.ts
  web/src/components/panels/index.tsx
  web/src/forms/settings/FeedForms.tsx
Labels: enhancement, backend, feeds

#341 feat(actions): reduce metadata collection
  internal/action/exec.go
  internal/action/run.go
Labels: enhancement, backend, actions

#339 feat(indexers): add PB
  internal/indexer/definitions/pbay.yaml
Labels: enhancement, backend, indexers

#350 feat(download-clients): add Transmission
  go.mod
  go.sum
  internal/action/run.go
  internal/action/transmission.go
  internal/domain/action.go
  internal/domain/client.go
  internal/download_client/connection.go
  web/src/domain/constants.ts
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/screens/filters/details.tsx
  web/src/types/Download.d.ts
Labels: enhancement, backend, Download client, actions

#351 feat(actions): watch dir create folder if not exists
  internal/action/run.go
Labels: enhancement, backend, actions

#353 fix(irc): connect join logic error
  internal/irc/handler.go
Labels: bug, backend, irc

#354 feat(irc): only join valid channels from invite
  internal/irc/handler.go
Labels: enhancement, backend, irc

#355 fix(autobrrctl): add missing logger
  cmd/autobrrctl/main.go
  internal/database/database.go
Labels: bug, backend

#356 feat(config): loglevel default options add trace
  config.toml
  internal/config/config.go
Labels: documentation, enhancement, backend

#357 fix(qbittorrent): remove client cache
  internal/action/qbittorrent.go
  pkg/qbittorrent/client.go
  pkg/qbittorrent/methods.go
Labels: bug, backend, Download client, actions

#358 build: pr upload binary artifacts
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: build

#359 feat(web): mobile UI improvements
  web/src/api/APIClient.ts
  web/src/components/alerts/index.tsx
  web/src/components/debug.tsx
  web/src/components/inputs/input_wide.tsx
  web/src/components/inputs/radio.tsx
  web/src/components/inputs/select.tsx
  web/src/components/modals/index.tsx
  web/src/components/panels/index.tsx
  web/src/domain/constants.ts
  web/src/forms/filters/FilterAddForm.tsx
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/forms/settings/FeedForms.tsx
  web/src/forms/settings/IndexerForms.tsx
  web/src/forms/settings/IrcForms.tsx
  web/src/forms/settings/NotificationForms.tsx
  web/src/screens/Settings.tsx
  web/src/screens/filters/details.tsx
  web/src/screens/filters/list.tsx
  web/src/screens/settings/Action.tsx
  web/src/screens/settings/Application.tsx
  web/src/screens/settings/DownloadClient.tsx
  web/src/screens/settings/Feed.tsx
  web/src/screens/settings/Indexer.tsx
  web/src/screens/settings/Irc.tsx
  web/src/screens/settings/Notifications.tsx
  web/src/screens/settings/Releases.tsx
Labels: enhancement, web

#361 fix(web) overflow issue on Recent Activities
  web/src/screens/dashboard/ActivityTable.tsx
Labels: web

#363 fix(feeds): torznab use link to download
  internal/feed/torznab.go
Labels: bug, backend, feeds

#364 docs: improve readme
  .github/images/autobrr-front.png
  .github/images/logo.png
  README.md
Labels: documentation, enhancement

#365 fix(web): tooltip text wrapping
  web/src/components/data-table/Cells.tsx
  web/src/components/tooltips/Tooltip.tsx
Labels: bug, web

#369 fix(actions): deluge v2 download file and check rules
  internal/action/deluge.go
Labels: bug, backend, Download client, actions

#370 fix(indexers): tn fix category parsing
  internal/indexer/definitions/torrentnetwork.yaml
Labels: bug, backend, indexers

#371 feat(indexers): btn improve parsing
  internal/domain/release.go
  internal/domain/releasetags.go
  internal/domain/releasetags_test.go
  internal/indexer/definitions/btn.yaml
Labels: enhancement, backend, indexers

#372 feat(filters): list actions count
  internal/database/filter.go
  internal/domain/filter.go
  web/src/screens/filters/list.tsx
  web/src/types/Filter.d.ts
Labels: enhancement, web, backend, actions

#379 fix(indexers): emp parse pattern id
  internal/indexer/definitions/emp.yaml
Labels: bug, backend, indexers

#373 feat(indexers): add subsplease
  internal/indexer/definitions/subsplease.yaml
Labels: enhancement, backend, indexers

#380 chore(server): update dependencies
  go.mod
  go.sum
  internal/domain/filter_test.go
Labels: backend

#382 fix(server): exclude tags from version check
  pkg/version/version.go
  pkg/version/version_test.go
Labels: enhancement, backend, settings, notifications

#383 feat(indexers): add nCore
  internal/indexer/definitions/ncore.yaml
Labels: enhancement, backend, indexers

#384 feat(indexers): add RetroFlix
  internal/indexer/definitions/retroflix.yaml
Labels: enhancement, backend, indexers

#385 feat(indexers): add ImmortalSeed
  internal/indexer/definitions/immortalseed.yaml
Labels: enhancement, backend, indexers

#386 fix(indexers): immortalseed settings parse
  internal/indexer/definitions/immortalseed.yaml
Labels: bug, backend, indexers
