Repository autobrr/autobrr, pull requests merged in 2022-06, with the labels that each got.

#288 fix(deps): update yarn lock
  web/yarn.lock
Labels: enhancement, build

#285 refactor: Started refactoring codebase for React 18.
  internal/http/auth.go
  web/package.json
  web/src/App.tsx
  web/src/components/debug.tsx
  web/src/components/inputs/common.tsx
  web/src/components/inputs/select.tsx
  web/src/components/inputs/text.tsx
  web/src/domain/routes.tsx
  web/src/forms/filters/FilterAddForm.tsx
  web/src/index.tsx
  web/src/reportWebVitals.ts
  web/src/screens/Base.tsx
  web/src/screens/Settings.tsx
  web/src/screens/auth/login.tsx
  web/src/screens/auth/logout.tsx
  web/src/screens/auth/onboarding.tsx
  web/src/screens/dashboard/ActivityTable.tsx
  web/src/screens/filters/details.tsx
  web/src/screens/filters/list.tsx
  web/src/screens/releases/ReleaseTable.tsx
  web/src/screens/settings/Irc.tsx
  web/src/setupTests.ts
  web/src/utils/index.ts
  web/yarn.lock
Labels: help wanted, web

#295 fix:(actions): exec shell expansion
  go.mod
  go.sum
  internal/action/exec.go
  internal/action/exec_test.go
  internal/logger/mock.go
Labels: bug, backend, actions

#297 fix(irc): append invite command on save
  internal/database/irc.go
  internal/domain/irc.go
  internal/irc/service.go
Labels: bug, backend, irc

#298 feat(indexers): add PT
  internal/indexer/definitions/pussytorrents.yaml
Labels: enhancement, indexers

#296 fix: mobile ux improvements
  web/src/components/data-table/Cells.tsx
  web/src/screens/filters/details.tsx
  web/src/screens/releases/Filters.tsx
  web/src/screens/releases/ReleaseTable.tsx
  web/src/screens/settings/DownloadClient.tsx
Labels: enhancement, web

#300 fix(download-clients): qBit transform speed limit from B to KB
  internal/action/qbittorrent.go
Labels: bug, backend, Download client, actions

#301 fix(download-clients): qbittorrent type ratelimit conversion error
  internal/action/qbittorrent.go
Labels: bug, backend, Download client, actions

#302 feat(releases): search in ui
  internal/database/release.go
  internal/domain/release.go
  internal/http/encoder.go
  internal/http/release.go
  internal/release/service.go
  web/src/api/APIClient.ts
  web/src/screens/dashboard/ActivityTable.tsx
  web/src/screens/releases/Filters.tsx
  web/src/screens/releases/ReleaseTable.tsx
Labels: enhancement, web, backend, releases

#305 fix(web): modal double state update
  web/src/screens/settings/Releases.tsx
Labels: bug, web

#308 fix(filters): postgres dl limits check
  internal/database/filter.go
Labels: bug, backend, filters

#309 fix(logging): timestamp and update pkg
  go.mod
  go.sum
  internal/irc/handler.go
  internal/logger/logger.go
Labels: bug, backend

#303 fix(indexers): don't die on failed load of custom-definitions
  internal/indexer/service.go
Labels: bug, backend, indexers

#310 feature(releases): optimize database indexes
  internal/database/migrate.go
Labels: enhancement, backend, releases

#311 fix(indexers): don't crash on empty custom-definition
  internal/indexer/service.go
Labels: bug, backend, indexers

#316 fix(web): correctly replace logout url
  web/src/components/alerts/ErrorPage.tsx
  web/src/screens/auth/login.tsx
  web/src/screens/auth/logout.tsx
Labels: web

#317 fix(indexers): duplicates in list
  internal/http/indexer.go
  internal/indexer/service.go
Labels: bug, backend, indexers

#318 fix(indexers): indexers store and update
  go.mod
  go.sum
  internal/indexer/service.go
  web/src/forms/settings/IndexerForms.tsx
Labels: bug, backend, indexers

#321 feat(build): update to Go 18
  .github/workflows/release.yml
  Dockerfile
  go.sum
Labels: docker, build

#315 feat(irc): improve reconnect and add notifications
  cmd/autobrr/main.go
  go.mod
  go.sum
  internal/domain/irc.go
  internal/domain/notification.go
  internal/events/subscribers.go
  internal/irc/handler.go
  internal/irc/service.go
  internal/notification/discord.go
  internal/notification/service.go
  test/integration/docker-compose.yml
  test/integration/ircd.yaml
  web/src/domain/constants.ts
  web/src/screens/settings/Irc.tsx
  web/src/types/Irc.d.ts
  web/src/types/Notification.d.ts
Labels: backend, irc
