Repository autobrr/autobrr, pull requests merged in 2022-05, with the labels that each got.

#259 fix(feeds): ttl and correct field types
  internal/database/feed.go
  internal/database/feed_cache.go
  internal/database/migrate.go
  internal/database/release.go
  internal/domain/feed.go
  internal/feed/torznab.go
Labels: bug, enhancement, backend, database

#260 fix(feeds): create with indexer id
  internal/domain/feed.go
Labels: bug, enhancement, backend

#261 feat(download-clients): qbt set re-announce opts
  internal/action/qbittorrent.go
  internal/database/action.go
  internal/database/migrate.go
  internal/domain/action.go
  web/src/components/inputs/switch.tsx
  web/src/screens/filters/details.tsx
  web/src/types/Filter.d.ts
Labels: enhancement, backend, Download client, actions

#262 fix(db): bad migration
  internal/database/migrate.go
Labels: bug, enhancement, backend

#264 feat(actions): qbit set ratio and seed time limits
  internal/action/qbittorrent.go
  internal/database/action.go
  internal/database/migrate.go
  internal/database/utils.go
  internal/domain/action.go
  web/src/components/inputs/input.tsx
  web/src/screens/filters/details.tsx
  web/src/types/Filter.d.ts
Labels: enhancement, web, backend, Download client, actions

#265 feat(filters): regex match release support list
  internal/domain/filter.go
  internal/domain/filter_test.go
Labels: enhancement, filters

#263 feat(actions): wait for the filter delay before performing actions
  internal/release/service.go
Labels: enhancement, backend, filters, actions

#271 fix(db): initial schema filter origins nullable
  internal/database/migrate.go
  web/src/forms/filters/FilterAddForm.tsx
Labels: bug, filters, database

#272 web: mobile improvements
  web/src/components/debug.tsx
  web/src/screens/Settings.tsx
  web/src/screens/filters/details.tsx
  web/src/utils/index.ts
Labels: bug, enhancement, web

#273 fix(filters): contains check empty
  internal/domain/filter.go
  internal/domain/filter_test.go
Labels: bug, backend, filters

#274 fix(indexers-irc): reload config on restart
  internal/announce/announce.go
  internal/domain/release.go
  internal/http/indexer.go
  internal/indexer/service.go
  internal/irc/handler.go
  web/src/forms/settings/IndexerForms.tsx
Labels: backend, indexers, irc

#266 feat(filters): add download limits
  internal/database/filter.go
  internal/database/migrate.go
  internal/database/release.go
  internal/domain/filter.go
  internal/domain/filter_test.go
  web/src/components/inputs/select.tsx
  web/src/domain/constants.ts
  web/src/screens/filters/details.tsx
  web/src/types/Filter.d.ts
Labels: enhancement, web, backend, filters

#276 fix(indexers): add
  internal/indexer/service.go
Labels: bug, backend, indexers

#277 refactor(irc): cleanup logging
  internal/irc/handler.go
Labels: enhancement, backend, irc

#245 feat(qbit): refactor url parse and add basic auth
  Dockerfile
  internal/action/qbittorrent.go
  internal/download_client/connection.go
  pkg/qbittorrent/client.go
  pkg/qbittorrent/client_test.go
  pkg/qbittorrent/methods.go
  web/src/forms/settings/DownloadClientForms.tsx
Labels: enhancement, backend, Download client

#279 docs: fixed dead urls in app
  .goreleaser.yml
  web/src/screens/Base.tsx
Labels: documentation

#281 fix(config): load sqlite from configdir
  internal/config/config.go
Labels: bug, backend, database

#283 feat(indexers): add bit-hdtv
  internal/indexer/definitions/bit-hdtv.yaml
Labels: enhancement, backend, indexers

#282 feat(indexers): add AL
  internal/indexer/definitions/acidlounge.yaml
Labels: enhancement, backend, indexers

#284 enhancement(web/logs): improved functionality
  web/package.json
  web/src/domain/react-table-config.d.ts
  web/src/screens/Logs.tsx
Labels: enhancement, web
