Repository autobrr/autobrr, pull requests merged in 2022-08, with the labels that each got.

#390 fix(scheduler): use time as opposed to cron fields
  internal/feed/service.go
  internal/scheduler/service.go
Labels: enhancement, backend, feeds

#391 fix(indexers): immortalseed irc addr
  internal/indexer/definitions/immortalseed.yaml
Labels: backend, irc

#392 feat(indexers): add HD-Space
  internal/indexer/definitions/hd-space.yaml
Labels: enhancement, backend, indexers

#394 feat(indexers): torrentsyndikat change releaseTags to tags
  internal/indexer/definitions/torrentsyndikat.yaml
Labels: enhancement, backend, indexers

#393 feat(actions): qbit add options content layout and skip hash check
  internal/action/qbittorrent.go
  internal/database/action.go
  internal/database/postgres.go
  internal/database/postgres_migrate.go
  internal/database/sqlite.go
  internal/database/sqlite_migrate.go
  internal/domain/action.go
  internal/filter/service.go
  pkg/qbittorrent/domain.go
  pkg/qbittorrent/domain_test.go
  web/src/domain/constants.ts
  web/src/screens/filters/details.tsx
  web/src/types/Filter.d.ts
Labels: enhancement, backend, Download client, actions

#396 feat(filters): add except origins
  internal/database/filter.go
  internal/database/postgres_migrate.go
  internal/database/sqlite_migrate.go
  internal/domain/filter.go
  internal/domain/filter_test.go
  internal/domain/releasetags.go
  web/src/screens/filters/details.tsx
  web/src/types/Filter.d.ts
Labels: enhancement, backend, filters

#397 fix(indexers): ggn fetch data from api
  pkg/ggn/ggn.go
Labels: bug, backend, indexers

#387 build: add darwin macos
  .github/workflows/docker.yml
  .goreleaser.yml
Labels: enhancement, build

#403 feat(indexers): nbl set tls and improve parsing
  internal/indexer/definitions/nebulance.yaml
Labels: enhancement, backend, indexers, irc

#404 fix(actions): lidarr properly handle rejected
  pkg/lidarr/lidarr.go
Labels: enhancement, backend, actions

#402 feat(indexers): add Hebits
  internal/indexer/definitions/Hebits.yaml
Labels: enhancement, backend, indexers

#406 feat(indexers): add Fuzer
  internal/indexer/definitions/fuzer.yaml
Labels: enhancement, backend, indexers

#399 fix(irc): rewrite handler pipeline
  go.mod
  go.sum
  internal/domain/irc.go
  internal/irc/handler.go
  internal/irc/service.go
  web/src/screens/settings/Irc.tsx
  web/src/types/Irc.d.ts
Labels: bug, enhancement, backend, irc

#407 feat(indexers): mam parse vip as freeleech
  internal/domain/release.go
  internal/domain/release_test.go
Labels: enhancement, backend, indexers, irc

#408 feat(api): add apikey support
  cmd/autobrr/main.go
  go.mod
  go.sum
  internal/api/service.go
  internal/database/api.go
  internal/database/postgres_migrate.go
  internal/database/sqlite_migrate.go
  internal/domain/api.go
  internal/http/action.go
  internal/http/apikey.go
  internal/http/auth.go
  internal/http/config.go
  internal/http/download_client.go
  internal/http/encoder.go
  internal/http/feed.go
  internal/http/filter.go
  internal/http/health.go
  internal/http/indexer.go
  internal/http/irc.go
  internal/http/middleware.go
  internal/http/notification.go
  internal/http/release.go
  internal/http/server.go
  web/src/api/APIClient.ts
  web/src/components/fields/text.tsx
  web/src/domain/routes.tsx
  web/src/forms/settings/APIKeyAddForm.tsx
  web/src/screens/Settings.tsx
  web/src/screens/settings/Api.tsx
  web/src/screens/settings/Application.tsx
  web/src/types/API.d.ts
Labels: enhancement, backend, api

#409 feat(filters): support partial update
  internal/database/filter.go
  internal/domain/filter.go
  internal/filter/service.go
  internal/http/filter.go
Labels: enhancement, backend, filters

#413 fix(indexers): red grab torrent id
  internal/indexer/definitions/red.yaml
Labels: bug, backend, indexers

#410 feat(feeds): add generic RSS support
  go.mod
  go.sum
  internal/domain/feed.go
  internal/domain/indexer.go
  internal/domain/release.go
  internal/feed/rss.go
  internal/feed/service.go
  internal/feed/torznab.go
  internal/indexer/definitions/rss_generic.yaml
  internal/indexer/service.go
  internal/scheduler/service.go
  web/src/forms/settings/FeedForms.tsx
  web/src/forms/settings/IndexerForms.tsx
  web/src/screens/settings/Feed.tsx
  web/src/screens/settings/Indexer.tsx
  web/src/types/Feed.d.ts
  web/src/types/Indexer.d.ts
Labels: backend, indexers, feeds

#414 feat(docker): expose default port
  Dockerfile
  Dockerfile.ci
Labels: enhancement, docker, build

#420 fix(config): improve container detection
  .dockerignore
  internal/api/service.go
  internal/config/config.go
Labels: bug, backend, docker, build

#421 feat(clients): add rTorrent support
  README.md
  go.mod
  go.sum
  internal/action/rtorrent.go
  internal/action/run.go
  internal/domain/action.go
  internal/domain/client.go
  internal/download_client/connection.go
  web/src/domain/constants.ts
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/screens/filters/action.tsx
  web/src/screens/filters/details.tsx
  web/src/types/Download.d.ts
Labels: enhancement, backend, Download client, actions

#428 fix(web): typos
  web/src/forms/settings/FeedForms.tsx
Labels: documentation, enhancement, backend

#381 feat(indexers): TorrentName templating
  go.mod
  go.sum
  internal/announce/announce.go
  internal/domain/indexer.go
  internal/domain/indexer_test.go
  internal/domain/release.go
  internal/indexer/definitions/animebytes.yaml
Labels: enhancement, backend, indexers, filters

#433 fix(filters): check `match other` and `except other`
  internal/domain/filter.go
  internal/domain/filter_test.go
Labels: bug, backend, filters

#444 feat(actions): implement TorrentDataRawBytes macro
  internal/action/exec.go
  internal/action/run.go
  internal/domain/macros.go
  internal/domain/release.go
  internal/filter/service.go
Labels: enhancement, backend, actions

#446 feat(macros): implement size
  internal/domain/macros.go
Labels: enhancement, backend, actions

#435 feat(indexers): add OppaiTime
  internal/indexer/definitions/oppaitime.yaml
Labels: enhancement, backend, indexers

#436 feat(indexers): add PolishTracker
  internal/indexer/definitions/polishtracker.yaml
Labels: enhancement, backend, indexers

#438 feat(indexers): add PolishSource
  internal/indexer/definitions/polishsource.yaml
Labels: enhancement, backend, indexers

#440 feat(indexers): add SceneHD
  internal/indexer/definitions/scenehd.yaml
Labels: enhancement, backend, indexers

#441 feat(indexers): add XSpeeds
  internal/indexer/definitions/xspeeds.yaml
Labels: enhancement, backend, indexers

#442 feat(indexers): add BitTorrentFiles
  internal/indexer/definitions/btfiles.yaml
Labels: enhancement, backend, indexers

#439 feat(indexers): add SpeedApp
  internal/indexer/definitions/speedapp.yaml
Labels: enhancement, backend, indexers

#448 fix(indexers): properly escape regex patterns
  internal/indexer/definitions/btfiles.yaml
  internal/indexer/definitions/scenehd.yaml
  internal/indexer/definitions/xspeeds.yaml
Labels: bug, backend, indexers
