Repository autobrr/autobrr, pull requests merged in 2022-11, with the labels that each got.

#519 fix(web): tooltips
  web/src/components/data-table/Cells.tsx
  web/src/screens/filters/details.tsx
Labels: web

#529 fix(download_client): improve no-client error
  internal/database/download_client.go
Labels: enhancement, web, backend, Download client

#531 fix(indexers): immortalseed regex
  internal/indexer/definitions/immortalseed.yaml
Labels: bug, backend, indexers

#532 fix(indexers): scenehd invite cmd
  internal/indexer/definitions/scenehd.yaml
Labels: bug, backend, indexers

#526 fix(cmd): add fallback tz information
  Dockerfile
  Dockerfile.ci
  cmd/autobrr/main.go
Labels: backend

#516 fix(indexers): GGn regex pattern
  internal/indexer/definitions/gazellegames.yaml
Labels: backend, indexers

#521 fix(web): download client table overflow, filter alerts, dubious wording
  web/src/components/data-table/Cells.tsx
  web/src/components/debug.tsx
  web/src/forms/settings/IrcForms.tsx
  web/src/screens/dashboard/ActivityTable.tsx
  web/src/screens/filters/details.tsx
  web/src/screens/settings/Application.tsx
  web/src/screens/settings/DownloadClient.tsx
Labels: web

#528 fix(web): infinitely retry queries, remove "ago" from age cells
  web/src/App.tsx
  web/src/components/data-table/Cells.tsx
Labels: web

#533 feat(indexers): add HUNO
  internal/domain/release.go
  internal/domain/release_test.go
  internal/indexer/definitions/huno.yaml
Labels: indexers

#534 fix(indexers): HUNO missing escapes on slashes
  internal/indexer/definitions/huno.yaml
Labels: bug, backend, indexers

#541 fix(indexers): HUNO fix parsing
  internal/indexer/definitions/huno.yaml
Labels: bug, backend, indexers

#540 fix(actions): watch dir name check torrent suffix
  internal/action/run.go
Labels: bug, enhancement, backend, actions

#542 feat(notifications): Notifiarr use auth header
  internal/notification/notifiarr.go
Labels: enhancement, backend, notifications

#538 fix(feeds): indexer identifier issues
  internal/database/feed.go
  internal/indexer/service.go
  web/src/forms/settings/IndexerForms.tsx
  web/src/types/Feed.d.ts
Labels: bug, backend, indexers, feeds

#547 build(ci): move back to hosted-runners
  .github/workflows/release.yml
Labels: build

#549 feat(download-clients): improve arr error handling
  pkg/lidarr/lidarr.go
  pkg/radarr/radarr.go
  pkg/radarr/radarr_test.go
  pkg/readarr/readarr.go
  pkg/sonarr/sonarr.go
Labels: enhancement, backend, Download client, actions
