Repository autobrr/autobrr, pull requests merged in 2023-03, with the labels that each got.

#543 feat: add usenet support
  internal/action/radarr.go
  internal/action/run.go
  internal/action/sabnzbd.go
  internal/action/sonarr.go
  internal/announce/announce.go
  internal/domain/action.go
  internal/domain/client.go
  internal/domain/feed.go
  internal/domain/indexer.go
  internal/domain/release.go
  internal/download_client/connection.go
  internal/feed/newznab.go
  internal/feed/service.go
  internal/indexer/service.go
  pkg/newznab/caps.go
  pkg/newznab/category.go
  pkg/newznab/feed.go
  pkg/newznab/newznab.go
  pkg/sabnzbd/sabnzbd.go
  web/src/components/inputs/radio.tsx
  web/src/domain/constants.ts
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/forms/settings/FeedForms.tsx
  web/src/forms/settings/IndexerForms.tsx
  web/src/screens/filters/action.tsx
  web/src/screens/settings/Indexer.tsx
  web/src/types/Download.d.ts
  web/src/types/Feed.d.ts
  web/src/types/Indexer.d.ts
Labels: enhancement, backend, indexers

#731 enhancement(web): stats and releases pretty loading
  web/src/screens/dashboard/ActivityTable.tsx
  web/src/screens/dashboard/Stats.tsx
  web/src/screens/releases/ReleaseTable.tsx
Labels: enhancement, web

#738 fix(indexers): ncore irc server change
  internal/indexer/definitions/ncore.yaml
Labels: bug, indexers, irc

#736 fix(filters): match `dv hdr`
  internal/domain/filter.go
  internal/domain/filter_test.go
Labels: bug, backend, filters

#725 fix(filters): quality multi select not closing
  web/src/components/inputs/select.tsx
Labels: bug, web

#715 feat(downloadclients): make fields required
  web/src/components/inputs/input_wide.tsx
  web/src/forms/settings/DownloadClientForms.tsx
Labels: web, Download client

#739 build: always run test job
  .github/workflows/release.yml
Labels: build

#740 build: force disable cgo
  .goreleaser.yml
Labels: build

#741 fix(indexers): add generic newznab definition
  internal/indexer/definitions/newznab_generic.yaml
Labels: backend, indexers

#742 chore: update go deps
  go.mod
  go.sum
Labels: backend

#743 fix(tags): `24bit Lossless` being tagged as `Lossless`
  internal/domain/release_test.go
  internal/domain/releasetags.go
  internal/domain/releasetags_test.go
Labels: bug, backend, filters, releases

#749 chore(web): settings update debug description
  web/src/screens/settings/Application.tsx
Labels: web

#748 enhancement(web): emphasize the need for HTTP in SABnzbd host URL
  web/src/forms/settings/DownloadClientForms.tsx
Labels: enhancement, web

#757 fix(macros): torrentdata parsing
  internal/action/exec.go
  internal/action/exec_test.go
  internal/action/run.go
  internal/action/service.go
  internal/domain/action.go
  internal/release/service.go
Labels: backend, actions, releases

#762 fix(newznab): Use valid usenet release protocol for Starrs
  internal/domain/event.go
  internal/domain/notification.go
  internal/domain/release.go
  internal/notification/notifiarr.go
Labels: backend, indexers, actions, feeds

#752 fix(autobrrctl): use brr-api instead of github directly for version check
  cmd/autobrrctl/main.go
Labels: api

#758 fix(filters): remove requirement for numberfields
  web/src/components/inputs/input.tsx
  web/src/screens/filters/action.tsx
  web/src/screens/filters/details.tsx
Labels: web, filters

#768 chore(indexers): properly capitalize Aither network
  internal/indexer/definitions/aither.yaml
Labels: backend, indexers

#684 feat(sqlite): commit WAL on startup
  internal/database/sqlite.go
Labels: backend, database

#755 feat(filters): import/export functionality
  web/src/screens/filters/details.tsx
  web/src/screens/filters/list.tsx
Labels: enhancement, web, filters

#756 feat(actions): rtorrent add folder rename toggle
  internal/action/rtorrent.go
  web/src/domain/constants.ts
  web/src/screens/filters/action.tsx
Labels: backend, Download client, actions

#763 fix(feeds): implement max_age for torznab/newznab
  internal/feed/newznab.go
  internal/feed/torznab.go
Labels: backend, indexers, feeds

#774 fix(releases): mismatched timestamp in list
  web/src/components/data-table/Cells.tsx
Labels: web, releases

#767 feat(logs): sanitize logfile on download
  internal/http/logs.go
  internal/http/logs_sanitize_test.go
  web/src/index.css
  web/src/screens/Logs.tsx
Labels: enhancement, web, backend, logs

#765 chore(http): set log level to trace
  internal/http/middleware.go
Labels: backend, api, logs

#775 fix(feeds): torznab newznab category parsing
  internal/feed/newznab.go
  internal/feed/torznab.go
  pkg/newznab/feed.go
  pkg/torznab/feed.go
  pkg/torznab/torznab.go
Labels: backend, releases, feeds

#776 feat(filters): navigate to edit page on filter creation
  web/src/api/APIClient.ts
  web/src/forms/filters/FilterAddForm.tsx
Labels: web, filters

#795 fix(filters): drop down menu z-index
  web/src/screens/filters/list.tsx
Labels: bug, web

#792 chore(deps): update rls parsing library
  go.mod
  go.sum
Labels: backend

#790 fix(indexers): pbay announce bot name
  internal/indexer/definitions/pbay.yaml
Labels: backend, indexers

#789 fix(feeds): check settings before unmarshalling
  internal/database/feed.go
Labels: backend, database

#785 feat(filters): use TextArea for webhook data field
  web/src/screens/filters/action.tsx
Labels: enhancement, web, actions

#783 enhancement(config): clarify logPath usage
  internal/config/config.go
Labels: backend

#782 feat(actions): add "don't start" option for rtorrent
  internal/action/rtorrent.go
  web/src/screens/filters/action.tsx
Labels: backend, Download client, actions

#779 refactor(logs): improve log sanitization performance
  internal/http/logs.go
  internal/http/logs_sanitize_test.go
Labels: enhancement, backend, logs

#797 refactor(logs): use zerolog instead of log
  internal/http/logs.go
Labels: backend, logs

#796 feat(indexers): add Locadora
  internal/indexer/definitions/locadora.yaml
Labels: backend, indexers

#772 feat(web): preserve sort order on Filters list
  web/src/screens/filters/list.tsx
  web/src/utils/Context.ts
Labels: enhancement, web

#800 enhancement(settings): make lists sortable
  web/src/screens/settings/DownloadClient.tsx
  web/src/screens/settings/Feed.tsx
  web/src/screens/settings/Indexer.tsx
  web/src/screens/settings/Irc.tsx
Labels: enhancement, web, settings

#773 feat(filters): regex validation for supported fields
  web/src/components/inputs/index.ts
  web/src/components/inputs/input.tsx
  web/src/components/tooltips/CustomTooltip.tsx
  web/src/screens/filters/details.tsx
  web/tailwind.config.js
Labels: enhancement, web, filters

#801 fix(feeds): torznab newznab pubdate parsing
  pkg/newznab/feed.go
  pkg/torznab/feed.go
Labels: bug, backend, indexers, feeds
