Repository autobrr/autobrr, pull requests merged in 2023-01, with the labels that each got.

#603 fix(releases): table sorting
  internal/database/release.go
Labels: bug, backend, database

#604 feat(releases): improve logscore parsing
  internal/domain/releasetags.go
  internal/domain/releasetags_test.go
  internal/indexer/definitions/orpheus.yaml
Labels: backend, indexers, filters, releases

#605 feat(filters): perfect flac disable fields
  web/src/components/inputs/common.tsx
  web/src/components/inputs/input.tsx
  web/src/components/inputs/select.tsx
  web/src/screens/filters/details.tsx
Labels: enhancement, web, filters

#609 feat(feeds): view latest RSS and Torznab feed
  internal/action/run.go
  internal/database/feed.go
  internal/domain/feed.go
  internal/feed/rss.go
  internal/feed/service.go
  internal/feed/torznab.go
  internal/http/feed.go
  internal/scheduler/service.go
  pkg/torznab/feed.go
  pkg/torznab/torznab.go
  web/src/screens/settings/Feed.tsx
Labels: enhancement, web, backend, feeds

#611 fix(web) reversed onChange for priority numberfield
  web/src/components/inputs/input.tsx
Labels: bug, web, filters

#608 enhancement(web): gray color for disabled checkboxes in dark mode
  web/src/components/inputs/common.tsx
Labels: web, filters

#607 refactor(web): fix indentation
  web/src/screens/settings/DownloadClient.tsx
Labels: web, settings

#622 docs: build shield
  README.md
Labels: documentation

#618 fix(indexers): subsplease baseurl
  internal/indexer/definitions/subsplease.yaml
Labels: bug, backend, indexers

#614 feat(indexers): add PixelHD
  internal/indexer/definitions/pixelhd.yaml
Labels: backend, indexers, irc

#615 feat(indexers): add PTN
  internal/indexer/definitions/ptn.yaml
Labels: backend, indexers, irc

#588 feat(indexers): add Aither
  internal/indexer/definitions/aither.yaml
Labels: backend, indexers, irc

#427 feat(indexers): add ANT
  internal/indexer/definitions/ant.yaml
Labels: enhancement, backend, indexers

#623 feat(indexers): add BitSexy
  internal/indexer/definitions/bitsexy.yaml
Labels: enhancement, backend, indexers, irc

#624 fix(indexers): subsplease regex
  internal/indexer/definitions/subsplease.yaml
Labels: enhancement, backend, indexers, irc

#625 feat(indexers): add SkipTheCommericals
  internal/indexer/definitions/skipthecommericals.yaml
Labels: enhancement, backend, indexers, irc

#621 feat(web): settings cosmetic improvements
  web/src/screens/Base.tsx
  web/src/screens/filters/details.tsx
  web/src/screens/settings/Api.tsx
  web/src/screens/settings/DownloadClient.tsx
  web/src/screens/settings/Feed.tsx
  web/src/screens/settings/Indexer.tsx
  web/src/screens/settings/Irc.tsx
  web/src/screens/settings/Notifications.tsx
  web/src/screens/settings/Releases.tsx
Labels: enhancement, web

#626 chore(indexers): remove TorrentDB
  internal/indexer/definitions/torrentdb.yaml
Labels: backend, indexers, irc

#627 docs: update readme
  README.md
Labels: documentation

#628 fix(feeds): view last run with baseurl
  web/src/screens/settings/Feed.tsx
Labels: bug, web, feeds, api

#629 feat(indexers): improve RED and OPS artist parsing
  internal/action/lidarr.go
  internal/domain/filter.go
  internal/indexer/definitions/orpheus.yaml
  internal/indexer/definitions/red.yaml
Labels: backend, indexers, irc, releases

#631 chore(indexers): remove Oppaitime
  internal/indexer/definitions/oppaitime.yaml
Labels: backend, indexers, irc

#633 feat(downloadclients): qBit add rule UploadSpeedThreshold
  internal/action/qbittorrent.go
  internal/domain/client.go
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/types/Download.d.ts
Labels: web, backend, Download client, actions, settings

#635 fix(indexers): IPT regex
  internal/indexer/definitions/iptorrents.yaml
Labels: enhancement, backend, indexers, irc

#632 feat(filters): support Language filtering
  internal/database/filter.go
  internal/database/postgres_migrate.go
  internal/database/sqlite_migrate.go
  internal/domain/filter.go
  internal/domain/release.go
  internal/domain/release_test.go
  internal/feed/rss_test.go
  pkg/torznab/torznab_test.go
  web/src/domain/constants.ts
  web/src/screens/filters/details.tsx
  web/src/types/Filter.d.ts
Labels: enhancement, web, backend, filters, database

#639 feat(irc): add with network password
  internal/indexer/definitions/aither.yaml
  web/src/forms/settings/IndexerForms.tsx
Labels: backend, indexers, irc

#640 chore(indexers): remove authkey from ANT
  internal/indexer/definitions/ant.yaml
Labels: backend, indexers, irc

#642 feat(indexers): add funfile
  internal/indexer/definitions/funfile.yaml
Labels: backend, indexers, irc

#641 feat(indexers): irc parse support ignoring lines
  internal/announce/announce.go
  internal/domain/indexer.go
  internal/indexer/definitions/pixelhd.yaml
Labels: backend, indexers, irc

#638 enhancement(web): autobrr logo link to dashboard
  web/src/screens/Base.tsx
  web/src/screens/dashboard/Stats.tsx
Labels: enhancement, web

#645 fix(filters): music type don't disable when perfect flac is selected
  web/src/screens/filters/details.tsx
Labels: web, filters

#646 fix(indexers): funfile single line parsing
  internal/indexer/definitions/funfile.yaml
Labels: enhancement, backend, indexers, irc

#651 fix(filters): Set NumberFields to required
  web/src/screens/filters/action.tsx
  web/src/screens/filters/details.tsx
Labels: enhancement, web, filters

#647 enhancement(feeds): torznab freeleech percentage
  internal/feed/torznab.go
Labels: backend, indexers, releases, feeds

#657 feat(logging): make log size and log backups configurable
  config.toml
  internal/config/config.go
  internal/domain/config.go
  internal/logger/logger.go
Labels: enhancement, backend

#654 fix(indexers): animebytes regex
  internal/indexer/definitions/animebytes.yaml
Labels: enhancement, backend, indexers

#656 fix(indexers): multiple definition regex pattern corrections
  internal/indexer/definitions/fuzer.yaml
  internal/indexer/definitions/hebits.yaml
  internal/indexer/definitions/iplay.yaml
  internal/indexer/definitions/ncore.yaml
  internal/indexer/definitions/retroflix.yaml
  internal/indexer/definitions/speedapp.yaml
  internal/indexer/definitions/torrentbytes.yaml
Labels: backend, indexers, irc

#652 feat(downloadclients): qBit rules add speed threshold condition
  internal/action/qbittorrent.go
  internal/domain/client.go
  web/src/components/inputs/input_wide.tsx
  web/src/components/inputs/select.tsx
  web/src/domain/constants.ts
  web/src/forms/settings/DownloadClientForms.tsx
Labels: backend, Download client, actions

#648 enhancement(web): filters list mobile friendly
  web/src/screens/Base.tsx
  web/src/screens/filters/list.tsx
Labels: enhancement, web

#634 enhancement(web): make settings pages uniform for desktop and mobile
  web/src/screens/settings/Api.tsx
  web/src/screens/settings/DownloadClient.tsx
  web/src/screens/settings/Feed.tsx
  web/src/screens/settings/Indexer.tsx
  web/src/screens/settings/Notifications.tsx
Labels: enhancement, web

#659 fix(web): filters list desktop and mobile friendly
  web/src/screens/filters/list.tsx
Labels: enhancement, web

#673 fix(indexers): new announcer for Nebulance
  internal/indexer/definitions/nebulance.yaml
Labels: backend, indexers, irc

#674 docs(filters): update placeholders for advanced filters
  web/src/screens/filters/details.tsx
Labels: documentation, web, filters

#676 fix(filters): enable IsScene parsing for value 1
  internal/domain/release.go
Labels: backend, indexers, irc, releases

#661 enhancement(web): styled scrollbars for webkit browser
  web/src/index.css
Labels: web, cosemetic

#662 chore(web): ignore eslint warnings
  web/.eslintrc.js
  web/src/components/inputs/input.tsx
  web/src/screens/Base.tsx
Labels: web

#681 fix(releases): check for duplicate tags
  internal/domain/release.go
Labels: backend, releases

#666 fix(indexers): Funfile download URL
  internal/indexer/definitions/funfile.yaml
Labels: backend, indexers, irc

#669 fix(filters): allow negative priority again
  web/src/screens/filters/details.tsx
Labels: web, filters

#668 fix(releases): force capture titles
  internal/domain/release.go
  internal/indexer/definitions/animebytes.yaml
Labels: backend, indexers, irc, releases

#682 feat(indexers): add LST
  internal/indexer/definitions/lst.yaml
Labels: backend, indexers, irc

#553 feat(download-client): add support for Porla
  internal/action/porla.go
  internal/action/run.go
  internal/domain/action.go
  internal/domain/client.go
  internal/download_client/connection.go
  pkg/porla/client.go
  pkg/porla/domain.go
  pkg/porla/methods.go
  web/src/domain/constants.ts
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/screens/filters/action.tsx
  web/src/types/Download.d.ts
Labels: enhancement, web, backend, Download client, actions
