Repository autobrr/autobrr, pull requests merged in 2023-02, with the labels that each got.

#687 fix(indexers): add default http baseurl for PTN
  internal/indexer/definitions/ptn.yaml
Labels: backend, indexers, irc

#685 fix(filters): add support for year-less titles
  go.mod
  go.sum
  internal/domain/filter_test.go
  internal/domain/release.go
  internal/domain/release_test.go
Labels: enhancement, backend, filters, releases

#680 enhancement(web): disable freeleech percent field if freeleech is enabled
  web/src/screens/filters/details.tsx
Labels: enhancement, web, filters

#663 feat(web): Add helper tooltips for inputs and link them to docs
  web/package.json
  web/src/components/inputs/common.tsx
  web/src/components/inputs/input.tsx
  web/src/components/inputs/input_wide.tsx
  web/src/components/inputs/select.tsx
  web/src/components/inputs/switch.tsx
  web/src/components/tooltips/CustomTooltip.css
  web/src/components/tooltips/CustomTooltip.tsx
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/forms/settings/IndexerForms.tsx
  web/src/index.tsx
  web/src/screens/filters/action.tsx
  web/src/screens/filters/details.tsx
  web/src/screens/settings/DownloadClient.tsx
  web/yarn.lock
Labels: documentation, enhancement, web

#690 feat: show new updates in dashboard
  .gitignore
  Makefile
  cmd/autobrr/main.go
  config.toml
  internal/config/config.go
  internal/config/config_test.go
  internal/domain/config.go
  internal/http/config.go
  internal/http/middleware.go
  internal/http/server.go
  internal/http/update.go
  internal/scheduler/jobs.go
  internal/scheduler/service.go
  internal/server/server.go
  internal/update/update.go
  pkg/version/version.go
  pkg/version/version_test.go
  web/src/api/APIClient.ts
  web/src/screens/Base.tsx
  web/src/screens/settings/Application.tsx
  web/src/types/Config.d.ts
  web/src/types/Irc.d.ts
  web/src/types/Update.d.ts
  web/src/utils/Context.ts
Labels: enhancement, web, backend, settings, api

#693 feat(indexers): add SkipTheTrailers (STT)
  internal/indexer/definitions/skipthetrailers.yaml
Labels: enhancement, backend, indexers

#667 fix(feeds): RSS improve torrent size parsing
  internal/domain/release.go
  internal/feed/rss.go
Labels: enhancement, backend, feeds

#694 fix(indexer): Fixed bad url for PTN
  internal/indexer/definitions/ptn.yaml
Labels: backend, indexers, irc

#696 fix(indexers): SkipTheTrailers identifier
  internal/indexer/definitions/skipthetrailers.yaml
Labels: bug, backend, indexers, irc

#697 fix(indexers) alpharatio infourl
  internal/indexer/definitions/alpharatio.yaml
Labels: backend, indexers, irc

#698 fix(indexers): Anthelion infourl
  internal/indexer/definitions/ant.yaml
Labels: backend, indexers, irc

#699 fix(indexers): hd-space infourl
  internal/indexer/definitions/hd-space.yaml
Labels: backend, indexers, irc

#701 fix(indexers): redacted infourl
  internal/indexer/definitions/red.yaml
Labels: backend, indexers, irc

#705 fix(indexers): TorrentBytes broken tracker use non-SSL link
  internal/indexer/definitions/torrentbytes.yaml
Labels: backend, indexers

#695 enhancement(database): improve log messages
  internal/database/postgres.go
  internal/database/sqlite.go
Labels: backend, database

#702 enhancement(web): login and onboarding work
  web/src/screens/auth/login.tsx
  web/src/screens/auth/onboarding.tsx
  web/src/screens/filters/action.tsx
Labels: web

#704 feat(settings): set log level
  internal/config/config.go
  internal/config/config_test.go
  internal/http/config.go
  web/src/domain/constants.ts
  web/src/domain/routes.tsx
  web/src/screens/Settings.tsx
  web/src/screens/settings/Application.tsx
  web/src/screens/settings/Irc.tsx
  web/src/screens/settings/Logs.tsx
  web/src/screens/settings/index.ts
  web/src/types/Config.d.ts
Labels: web, backend, settings

#709 enhancement(web): reduce tooltip icon contrast
  web/src/components/tooltips/CustomTooltip.tsx
  web/src/domain/routes.tsx
  web/src/screens/Base.tsx
  web/src/screens/auth/login.tsx
  web/src/screens/filters/details.tsx
Labels: web, cosemetic

#706 feat(logs): list log files and make downloadable
  internal/http/logs.go
  internal/http/server.go
  web/src/api/APIClient.ts
  web/src/screens/Logs.tsx
  web/src/screens/settings/Application.tsx
  web/src/screens/settings/Logs.tsx
  web/src/types/Config.d.ts
Labels: web, backend, settings, api

#710 build(docker): add pkg `jq`
  Dockerfile
  Dockerfile.ci
Labels: docker, build

#713 fix(web): fixed baseurl for log downloads
  web/src/screens/Logs.tsx
Labels: bug, web

#716 fix(releases): parse isScene as Origins SCENE
  internal/domain/release.go
  internal/domain/release_test.go
  internal/feed/rss_test.go
Labels: bug, backend, filters, releases

#717 fix(web): Logs page scroll to bottom
  web/src/screens/Logs.tsx
Labels: bug, web

#719 fix(web): reverted freeleech lock mechanism
  web/src/screens/filters/details.tsx
Labels: bug, web, filters

#711 feat(download-clients): porla implement rules
  internal/action/porla.go
  internal/action/run.go
  internal/download_client/connection.go
  pkg/jsonrpc/jsonrpc.go
  pkg/porla/client.go
  pkg/porla/domain.go
  pkg/porla/methods.go
  web/src/forms/settings/DownloadClientForms.tsx
  web/src/screens/filters/action.tsx
Labels: web, backend, Download client, actions

#733 feat(macros): add sprig functions to macros
  internal/domain/macros.go
  internal/domain/macros_test.go
Labels: backend, actions, releases

#729 feat(indexers): add PTFiles (PTF)
  internal/indexer/definitions/ptfiles.yaml
Labels: enhancement, backend, indexers

#730 feat(releases): support magnet links
  internal/action/deluge.go
  internal/action/exec.go
  internal/action/lidarr.go
  internal/action/porla.go
  internal/action/qbittorrent.go
  internal/action/radarr.go
  internal/action/readarr.go
  internal/action/rtorrent.go
  internal/action/run.go
  internal/action/sonarr.go
  internal/action/transmission.go
  internal/action/whisparr.go
  internal/database/feed.go
  internal/domain/feed.go
  internal/domain/macros.go
  internal/domain/release.go
  internal/feed/rss.go
  internal/feed/service.go
  internal/feed/torznab.go
  internal/filter/service.go
  pkg/lidarr/lidarr.go
  pkg/porla/domain.go
  pkg/radarr/radarr.go
  pkg/readarr/readarr.go
  pkg/sonarr/sonarr.go
  pkg/whisparr/whisparr.go
  web/src/components/inputs/input_wide.tsx
  web/src/components/inputs/select_wide.tsx
  web/src/domain/constants.ts
  web/src/forms/settings/FeedForms.tsx
  web/src/forms/settings/IndexerForms.tsx
  web/src/types/Feed.d.ts
Labels: backend, Download client, indexers, actions, releases, feeds, api

#726 chore(deps): update Go to 1.20
  .dockerignore
  .github/workflows/release.yml
  Dockerfile
  ci.Dockerfile
  go.mod
Labels: docker, build
