Repository autobrr/autobrr, pull requests merged in 2025-07, with the labels that each got.

#2117 fix(filters): multiple year ranges check
  internal/domain/filter.go
  internal/domain/filter_test.go
Labels: bug, backend, filters

#2112 feat(indexers): add HappyFappy
  internal/indexer/definitions/happyfappy.yaml
Labels: indexers, definitions, indexers:irc

#2122 fix(release): reduce log spam for indexers without active filters
  internal/release/service.go
Labels: backend, logs
